// @ts-nocheck — auto-generated by Soroban CLI from local wasm, do not edit manually
import { Buffer } from "buffer";
import { Address } from "@stellar/stellar-sdk";
import {
  AssembledTransaction,
  Client as ContractClient,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";
import type {
  u32,
  i32,
  u64,
  i64,
  u128,
  i128,
  u256,
  i256,
  Option,
  Timepoint,
  Duration,
} from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";

if (typeof window !== "undefined") {
  //@ts-ignore Buffer exists
  window.Buffer = window.Buffer || Buffer;
}





/**
 * One entry of a `Goal` rule. Deposits fill `pocket` up to `target`, then move on.
 */
export interface Goal {
  pocket: string;
  target: i128;
}

/**
 * How a user's incoming deposit is divided across pockets.
 */
export type SplitRule = {tag: "Fixed", values: readonly [Array<Allocation>]} | {tag: "Goal", values: readonly [Array<Goal>, string]};


/**
 * One slice of a `Fixed` rule. `bps` is basis points (1/100 of a percent).
 */
export interface Allocation {
  bps: u32;
  pocket: string;
}

export interface Client {
  /**
   * Construct and simulate a rule transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * The caller's split rule, if configured.
   */
  rule: ({user}: {user: string}, options?: MethodOptions) => Promise<AssembledTransaction<Option<SplitRule>>>

  /**
   * Construct and simulate a token transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * The stablecoin this vault deposits/withdraws.
   */
  token: (options?: MethodOptions) => Promise<AssembledTransaction<string>>

  /**
   * Construct and simulate a deposit transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Deposit `amount` stroops of the vault token and split it across pockets.
   * The caller must have a split rule configured first.
   */
  deposit: ({user, amount}: {user: string, amount: i128}, options?: MethodOptions) => Promise<AssembledTransaction<null>>

  /**
   * Construct and simulate a pockets transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * All of a user's pocket balances.
   */
  pockets: ({user}: {user: string}, options?: MethodOptions) => Promise<AssembledTransaction<Map<string, i128>>>

  /**
   * Construct and simulate a set_rule transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Set (or replace) the caller's split rule.
   */
  set_rule: ({user, rule}: {user: string, rule: SplitRule}, options?: MethodOptions) => Promise<AssembledTransaction<null>>

  /**
   * Construct and simulate a withdraw transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Withdraw `amount` stroops from a specific pocket back to the caller.
   */
  withdraw: ({user, pocket, amount}: {user: string, pocket: string, amount: i128}, options?: MethodOptions) => Promise<AssembledTransaction<null>>

  /**
   * Construct and simulate a pocket_balance transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Balance of a single pocket.
   */
  pocket_balance: ({user, pocket}: {user: string, pocket: string}, options?: MethodOptions) => Promise<AssembledTransaction<i128>>

}
export class Client extends ContractClient {
  static async deploy<T = Client>(
        /** Constructor/Initialization Args for the contract's `__constructor` method */
        {token}: {token: string},
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        /** The hash of the Wasm blob, which must already be installed on-chain. */
        wasmHash: Buffer | string;
        /** Salt used to generate the contract's ID. Passed through to {@link Operation.createCustomContract}. Default: random. */
        salt?: Buffer | Uint8Array;
        /** The format used to decode `wasmHash`, if it's provided as a string. */
        format?: "hex" | "base64";
      }
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy({token}, options)
  }
  constructor(public readonly options: ContractClientOptions) {
    super(
      new ContractSpec([ "AAAAAQAAAFBPbmUgZW50cnkgb2YgYSBgR29hbGAgcnVsZS4gRGVwb3NpdHMgZmlsbCBgcG9ja2V0YCB1cCB0byBgdGFyZ2V0YCwgdGhlbiBtb3ZlIG9uLgAAAAAAAAAER29hbAAAAAIAAAAAAAAABnBvY2tldAAAAAAAEQAAAAAAAAAGdGFyZ2V0AAAAAAAL",
        "AAAAAAAAACdUaGUgY2FsbGVyJ3Mgc3BsaXQgcnVsZSwgaWYgY29uZmlndXJlZC4AAAAABHJ1bGUAAAABAAAAAAAAAAR1c2VyAAAAEwAAAAEAAAPoAAAH0AAAAAlTcGxpdFJ1bGUAAAA=",
        "AAAAAgAAADhIb3cgYSB1c2VyJ3MgaW5jb21pbmcgZGVwb3NpdCBpcyBkaXZpZGVkIGFjcm9zcyBwb2NrZXRzLgAAAAAAAAAJU3BsaXRSdWxlAAAAAAAAAgAAAAEAAAAxU3RhdGljIHBlcmNlbnRhZ2VzLiBBbGwgYGJwc2AgbXVzdCBzdW0gdG8gMTBfMDAwLgAAAAAAAAVGaXhlZAAAAAAAAAEAAAPqAAAH0AAAAApBbGxvY2F0aW9uAAAAAAABAAAARlByaW9yaXR5LW9yZGVyZWQgZ29hbHMgcGx1cyBhbiBvdmVyZmxvdyBwb2NrZXQgZm9yIGFueXRoaW5nIGxlZnQgb3Zlci4AAAAAAARHb2FsAAAAAgAAA+oAAAfQAAAABEdvYWwAAAAR",
        "AAAAAAAAAC1UaGUgc3RhYmxlY29pbiB0aGlzIHZhdWx0IGRlcG9zaXRzL3dpdGhkcmF3cy4AAAAAAAAFdG9rZW4AAAAAAAAAAAAAAQAAABM=",
        "AAAAAQAAAEhPbmUgc2xpY2Ugb2YgYSBgRml4ZWRgIHJ1bGUuIGBicHNgIGlzIGJhc2lzIHBvaW50cyAoMS8xMDAgb2YgYSBwZXJjZW50KS4AAAAAAAAACkFsbG9jYXRpb24AAAAAAAIAAAAAAAAAA2JwcwAAAAAEAAAAAAAAAAZwb2NrZXQAAAAAABE=",
        "AAAAAAAAAHxEZXBvc2l0IGBhbW91bnRgIHN0cm9vcHMgb2YgdGhlIHZhdWx0IHRva2VuIGFuZCBzcGxpdCBpdCBhY3Jvc3MgcG9ja2V0cy4KVGhlIGNhbGxlciBtdXN0IGhhdmUgYSBzcGxpdCBydWxlIGNvbmZpZ3VyZWQgZmlyc3QuAAAAB2RlcG9zaXQAAAAAAgAAAAAAAAAEdXNlcgAAABMAAAAAAAAABmFtb3VudAAAAAAACwAAAAA=",
        "AAAAAAAAACBBbGwgb2YgYSB1c2VyJ3MgcG9ja2V0IGJhbGFuY2VzLgAAAAdwb2NrZXRzAAAAAAEAAAAAAAAABHVzZXIAAAATAAAAAQAAA+wAAAARAAAACw==",
        "AAAAAAAAAClTZXQgKG9yIHJlcGxhY2UpIHRoZSBjYWxsZXIncyBzcGxpdCBydWxlLgAAAAAAAAhzZXRfcnVsZQAAAAIAAAAAAAAABHVzZXIAAAATAAAAAAAAAARydWxlAAAH0AAAAAlTcGxpdFJ1bGUAAAAAAAAA",
        "AAAAAAAAAERXaXRoZHJhdyBgYW1vdW50YCBzdHJvb3BzIGZyb20gYSBzcGVjaWZpYyBwb2NrZXQgYmFjayB0byB0aGUgY2FsbGVyLgAAAAh3aXRoZHJhdwAAAAMAAAAAAAAABHVzZXIAAAATAAAAAAAAAAZwb2NrZXQAAAAAABEAAAAAAAAABmFtb3VudAAAAAAACwAAAAA=",
        "AAAAAAAAADNCaW5kIHRoZSB2YXVsdCB0byB0aGUgc2luZ2xlIHN0YWJsZWNvaW4gaXQgYWNjZXB0cy4AAAAADV9fY29uc3RydWN0b3IAAAAAAAABAAAAAAAAAAV0b2tlbgAAAAAAABMAAAAA",
        "AAAAAAAAABtCYWxhbmNlIG9mIGEgc2luZ2xlIHBvY2tldC4AAAAADnBvY2tldF9iYWxhbmNlAAAAAAACAAAAAAAAAAR1c2VyAAAAEwAAAAAAAAAGcG9ja2V0AAAAAAARAAAAAQAAAAs=" ]),
      options
    )
  }
  public readonly fromJSON = {
    rule: this.txFromJSON<Option<SplitRule>>,
        token: this.txFromJSON<string>,
        deposit: this.txFromJSON<null>,
        pockets: this.txFromJSON<Map<string, i128>>,
        set_rule: this.txFromJSON<null>,
        withdraw: this.txFromJSON<null>,
        pocket_balance: this.txFromJSON<i128>
  }
}